name: Publish Configurations on Release

on:
  release:
    types:
      - "released"

permissions:
  contents: write

jobs:
   release:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Login to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish Configuration to NPM
        run: npm publish --verbose --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
